repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.10.1
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export

  # - repo: https://github.com/python-poetry/poetry-plugin-export
  #   rev: 1.8.0
  #   hooks:
  #     - id: poetry-export
  #       args: ['--no-cache', '-f', 'requirements.txt', '-o', 'requirements.txt']
