[tool.poetry]
name = "archie"
version = "0.1.0"
description = ""
authors = ["f0e <7321764+f0e@users.noreply.github.com>"]
readme = "readme.md"
repository = "https://github.com/f0e/archie"
classifiers = [
    "Topic :: System :: Archiving",
    "Topic :: System :: Archiving :: Backup",
    "Topic :: Multimedia :: Video",
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
yt-dlp = "^2023.7.6"
sqlalchemy = "^2.0.20"
requests = "^2.31.0"
dacite = "^1.8.1"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
pre-commit = "^3.4.0"

[tool.poetry.scripts]
archie = 'archie.cli:archie'

[tool.poe.tasks.format-isort]
help = "Run isort on the code base"
cmd = "isort ."

[tool.poe.tasks.format-black]
help = "Run black on the code base"
cmd = "black ."

[tool.poe.tasks.format]
help = "Run formating tools on the code base"
sequence = ["format-isort", "format-black"]


[tool.black]
line-length = 160

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
